Blog_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogapp', include('blogapp.urls')),
    path(r'captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from django.urls import path
from .views import dashboard, register, compose, search_users
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blogapp'

urlpatterns = [
    path('register/', register, name='register'),
    path('dashboard/', dashboard, name='dashboard'),
    path('compose/', compose, name='compose'),
    path('search_users/', search_users, name='search_users'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='blogapp/logged_out.html'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogapp/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
import os

# Create your models here.

class UserRegistrationModel(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class Post(models.Model):
    image_storage = FileSystemStorage(
        # Physical file location ROOT
        location=os.path.join(settings.MEDIA_ROOT, 'blogapp'),
        # Url for file
        base_url=os.path.join(settings.MEDIA_URL, 'blogapp')
    )

    def image_directory_path(self, filename):
        return os.path.join('pics', filename)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    description = models.TextField()
    image = models.ImageField(blank=True, upload_to=image_directory_path, storage=image_storage)
    date_posted = models.DateTimeField(auto_now_add=True)
    is_public = models.BooleanField(default=True)

    def __str__(self):
        return self.title

blogapp/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import MinimumLengthValidator, NumericPasswordValidator, validate_password
from django import forms
from captcha.fields import CaptchaField
from .models import Post


class UserRegistration(forms.ModelForm):

    password = forms.CharField(label='Password', widget=forms.PasswordInput())
    password_conf = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)
    captcha = CaptchaField()

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def clean(self):
        cleaned_data = super(UserRegistration, self).clean()
        password = cleaned_data.get('password')
        conf_pass = cleaned_data.get('password_conf')

        if password != conf_pass:
            self.add_error(field='password_conf', error="Both Passwords don't match")

        validate_password(password=password)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','image','description','is_public']

        widgets = {
            'title': forms.TextInput(attrs = {
                'class': 'form-control',
                'placeholder': 'Enter a title'
            }),

            'description': forms.Textarea(attrs = {
                'class': 'form-control',
                'placeholder': 'Write your post',
            })
        }

blogapp/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import UserRegistration, PostForm
from django.contrib import messages
from .models import Post


# Create your views here.

def register(request):
    if request.method == 'POST':
        form = UserRegistration(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(
                form.cleaned_data.get('password')
            )
            new_user.save()
            return render(request, 'blogapp/register_done.html')
    else:
        form = UserRegistration()

    context = {
        "form": form
    }

    return render(request, 'blogapp/register.html', context=context)

@login_required
def dashboard(request):
    public_posts = Post.objects.filter(
        user=request.user,
        is_public=True,
    ).order_by('-date_posted')

    private_posts = Post.objects.filter(
        user=request.user,
        is_public=False,
    ).order_by('-date_posted')

    context = {
        'public_posts': public_posts,
        'private_posts': private_posts,
        'welcome': "Welcome to your dashboard"
    }

    return render(request, "blogapp/dashboard.html", context=context)


@login_required
def compose(request):
    if (request.method == 'POST'):
        form = PostForm(request.POST, request.FILES)
        if (form.is_valid()):
            cd = form.cleaned_data
            if (cd.get('image')):
                image = request.FILES['image']
            else:
                image = ''

            post = Post(user=request.user,
                        title=cd.get('title'),
                        description=cd.get('description'),
                        image=image,
                        is_public=cd['is_public']
                        )
            post.save()
            return redirect(reverse('blogapp:dashboard'))

    else:
        form = PostForm()

    context = {
        "write": "Write an Article",
        'form': form
    }

    return render(request, "blogapp/compose.html", context=context)

def search_users(request):
    if(request.method == 'POST'):
        user = request.POST.get('search_for')
        user = User.objects.filter(username = user)
        if(user.exists()):
            user = user[0]
            public_posts = Post.objects.filter(
                        user = user,
                        is_public = True,
                    ).order_by('-date_posted')

            context = {
                'public_posts': public_posts,
                'search_for': user
            }
            return render(request,"blogapp/dashboard.html", context=context)
        else:
            messages.warning(request, 'USER DOES NOT EXISTS')
    return render(request,"blogapp/dashboard.html")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> App {% block title %}{% endblock title %} </title>
</head>
<body>
    {% include "blogapp/../navbar.html" %}
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>

</body>
</html>

templates/blogapp/compose.html
{% extends "blogapp/../base.html" %}
{%  block title %} Compose {% endblock title %}
{%  block content %}
    <h1> {{ write }} </h1>

    <form action="{% url 'blogapp:compose' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="title"> Title </label>
        {{ form.title }}
        <hr>

        <label for="description"> Description </label>
        {{ form.description }}
        <label for="image"> Add image </label>
        {{ form.image }}
        <hr>

        {{ form.is_public }}
        <label for="">Post as public</label>

        <button> POST </button>
    </form>

{% endblock content %}

templates/blogapp/dashboard.html
{% extends "blogapp/../base.html" %}
{% block title %} Dashboard {% endblock title %}
{% block content %}
    <h1>{{ welcome }}</h1>

    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}

    <div>
        {% if public_posts %}
            <p class="text-center">
                PUBLIC POSTS
                {% if search_for %}
                    OF {{ search_for }}
                {% endif %}
            </p>

        {% endif %}

        {% for post in public_posts %}
            <p> {{ post.title }} </p>
            <p> {{ post.description }} </p>
            {% if post.image %}
                <img src="{{ post.image.url }}"
                style="height: 20rem; width: 20rem;"
                alt="">
            {% endif %}
        {% empty %}
            <h1>No public posts available</h1>
        {% endfor %}
    </div>

{% endblock content %}

templates/blogapp/edit.html
{% extends "blogapp/../base.html" %}
{% block title %}Edit{% endblock title %}
{% block content %}
<h2>Edit your account</h2>
<p>You can edit your account using the follow form</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

templates/blogapp/logged_out.html
{% extends "blogapp/../base.html" %}
{% block title %}Logged out{% endblock %}
{% block content %}
<h1>Logged out</h1>
<p>
    You have been successfully logged out.
    <hr>
    You can <a href="{% url 'blogapp:login' %}">log-in again</a>.
</p>
{% endblock %}

templates/blogapp/register.html
{% extends "blogapp/../base.html" %}
{% load bootstrap4 %}
{% block title %}Registration{% endblock title %}
{% block content %}

{% if form.errors %}
    
{% endif %}
    
<form action="" method="post" class="form container">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

templates/blogapp/register_done.html
{% extends "blogapp/../base.html" %}
{% block content %}
<h1>Welcome {{ new_user.first_name }}!</h1>
<p>Your account has been successfully created. Now you can <a href="{% url 'blogapp:login' %}">log in</a>.</p>
{% endblock content %}

templates/navbar.html
{% if request.user.is_authenticated %}
    <ul>
        <li>
            <a href="{% url 'blogapp:dashboard' %}"> Home </a>
            <a href="{% url 'blogapp:compose' %}"> Compose Article</a>
            <form action="{% url 'blogapp:search_users' %}" method="POST">
                {% csrf_token %}
                <input type="text" name="search_for" placeholder="Search users">
                <button type="submit" style="visibility: hidden;"> </button>
            </form>
        </li>
    </ul>
{% endif %}
<span>
    {% if request.user.is_authenticated %}
    <a href="{% url 'blogapp:logout' %}">Logout</a>
    Hello @ <i>{{user.username}}</i>

    {% else %}

    <div>
        <a href="{% url 'blogapp:login' %}"> Log-in </a>
        <a href="{% url 'blogapp:register' %}"> Register </a>
    </div>

    {% endif %}
</span>